name: test_env_heasoft

channels:
  - https://heasarc.gsfc.nasa.gov/FTP/software/conda/
  - conda-forge
  - defaults
  
dependencies:
  - numpy
  - pyyaml>=5.1
  - astropy
  - scipy
  - numdifftools
  - hdf5
  - pytables
  - pandas>=0.23
  - dill
  #- wcslib
  - future
  - heasoft
  - numba
  - h5py
  - libgfortran
  - omegaconf
  - colorama
  - rich
  - joblib
