name: test_env

channels:
  - conda-forge
  - defaults
  
dependencies:
  - numpy
  - pyyaml>=5.1
  - astropy
  - scipy
  - numdifftools
  - hdf5
  - pytables
  - pandas>=0.23
  - dill
  - wcslib
  - future
  - numba
  - h5py
  - libgfortran
  - omegaconf
  - colorama
  - rich
  - joblib
